In [ ]:
'''
=================================================
Milestone 1

Nama  : Herlina
Batch : CODA-RMT-018

Program ini dibuat untuk mengambil informasi dari website dan diterjemahkan dalam sebuah data 
=================================================
'''

# data manipulation or dataframe
import pandas as pd

# webscraping
from selenium import webdriver
from bs4 import BeautifulSoup
import time

In [8]:
# empty list
names = []
brands =[]
prices = []
imgs = []
diskon = []

# create driver
driver = webdriver.Safari()

# loop certain pages
for num_page in range(1, 5):
    # link
    url = f'https://www.kickavenue.com/search/sneakers?sex=F'

    # access the website
    driver.get(url)

    # delay / time sleep
    time.sleep(5)

    # Scroll
    max_scroll = 20
    count = 0

    while len(names) < 50 and count < max_scroll:
        driver.execute_script ("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(10)
        count += 1
    
    # fetch html components
    html = driver.page_source

    # parse
    soup = BeautifulSoup(html, "html.parser")

    # get box element
    boxes = soup.find_all('a', {'target':'_self'})

    # looping box
    for box in boxes:

        # get name
        try:
            name = box.find('h2', {'class':'price-tag'})
            names.append(name.get_text())
        except:
            names.append(None)
        
        # get brand
        try:
            brand = box.find('span', {'class':'price-tag brand'})
            brands.append(brand.get_text())
        except:
            brand.append(None)

        # get price
        try:
            price = box.find('span', {'class':'currency-tag currency-tag__black text-left price-tag text-bold'})
            prices.append(price.get_text())
        except:
            prices.append(None)

        # get image url
        try:
            img = box.find('img', {'class':'card-img'})
            imgs.append(img['src'])
        except:
            imgs.append(None)
        
        # get diskon 
        try:
            el_diskon = box.find('span', {'class':'currency-tag currency-tag__default text-left price-tag slashed'})
            diskon.append(el_diskon.get_text())
        except:
            diskon.append(None)


driver.quit()

In [9]:
data = pd.DataFrame(
    {
        'nama produk':names,
        'brand produk':brands,
        'harga produk':prices,
        'link gambar':imgs,
        'diskon':diskon
    }
)

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1242 entries, 0 to 1241
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nama produk   1242 non-null   str
 1   brand produk  1242 non-null   str
 2   harga produk  1242 non-null   str
 3   link gambar   1242 non-null   str
 4   diskon        520 non-null    str
dtypes: str(5)
memory usage: 48.6 KB

In [10]:
data

,nama produk,brand produk,harga produk,link gambar,diskon
0,Puma Speedcat Ballet Lace Frosted Ivory Ruby S...,Puma,"IDR 1,770,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1,Nike P-6000 White Elemental Pink Metallic Silv...,Nike,"IDR 1,300,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,729,000"
2,Puma Speedcat Ballet Lace Ruby Shimmer Frosted...,Puma,"IDR 1,800,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
3,Puma Speedcat Ballet Black Mauve Mist (Women's),Puma,"IDR 1,250,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,320,000"
4,Puma Speedcat Ballet Lace Silver (Women's),Puma,"IDR 1,640,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
...,...,...,...,...,...
1237,Adidas Samba Jane Sandy Pink Cream White Gum (...,Adidas,"IDR 1,600,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1238,Nike Vomero Plus White Dark Hazel Sanddrift Go...,Nike,"IDR 1,300,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 3,135,000"
1239,Adidas Samba Jane Crystal Sky Cream White (Wom...,Adidas,"IDR 1,700,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1240,Air Jordan 1 Low Panda (2023) (Women's),Air Jordan,"IDR 1,320,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1241,Nike Dunk Low Gorge Green Navy (Women's),Nike,"IDR 1,180,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,549,000"

In [11]:
data.to_csv('coda_P0M1_Data_Kotor_Herlina.csv',index=False)

In [12]:
# Buka data yang sudah di save. Jangan menggunakan data sebelumnya yang masih diolah
df = pd.read_csv('coda_P0M1_Data_Kotor_Herlina.csv')

In [13]:
df

,nama produk,brand produk,harga produk,link gambar,diskon
0,Puma Speedcat Ballet Lace Frosted Ivory Ruby S...,Puma,"IDR 1,770,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1,Nike P-6000 White Elemental Pink Metallic Silv...,Nike,"IDR 1,300,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,729,000"
2,Puma Speedcat Ballet Lace Ruby Shimmer Frosted...,Puma,"IDR 1,800,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
3,Puma Speedcat Ballet Black Mauve Mist (Women's),Puma,"IDR 1,250,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,320,000"
4,Puma Speedcat Ballet Lace Silver (Women's),Puma,"IDR 1,640,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
...,...,...,...,...,...
1237,Adidas Samba Jane Sandy Pink Cream White Gum (...,Adidas,"IDR 1,600,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1238,Nike Vomero Plus White Dark Hazel Sanddrift Go...,Nike,"IDR 1,300,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 3,135,000"
1239,Adidas Samba Jane Crystal Sky Cream White (Wom...,Adidas,"IDR 1,700,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1240,Air Jordan 1 Low Panda (2023) (Women's),Air Jordan,"IDR 1,320,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1241,Nike Dunk Low Gorge Green Navy (Women's),Nike,"IDR 1,180,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,549,000"

In [14]:
# Menarik 10 data teratas dalam data sneaker wanita di website Kickavenue
df.head(10)

,nama produk,brand produk,harga produk,link gambar,diskon
0,Puma Speedcat Ballet Lace Frosted Ivory Ruby S...,Puma,"IDR 1,770,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1,Nike P-6000 White Elemental Pink Metallic Silv...,Nike,"IDR 1,300,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,729,000"
2,Puma Speedcat Ballet Lace Ruby Shimmer Frosted...,Puma,"IDR 1,800,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
3,Puma Speedcat Ballet Black Mauve Mist (Women's),Puma,"IDR 1,250,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,320,000"
4,Puma Speedcat Ballet Lace Silver (Women's),Puma,"IDR 1,640,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
5,Puma Speedcat Ballet Silver (Women's),Puma,"IDR 1,100,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,299,000"
6,Puma Speedcat Ballet Dark Chocolate (Women's),Puma,"IDR 1,260,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
7,Puma Speedcat Ballet Lace Black (Women's),Puma,"IDR 1,530,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
8,Adidas Samba Jane Preloved Brown (Women's),Adidas,"IDR 1,810,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
9,Nike Dunk Low Cacao Wow (Women's),Nike,"IDR 1,100,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,650,000"

In [15]:
# Menarik 10 data terbawah dalam data sneaker wanita di website Kickavenue
df.tail(10)

,nama produk,brand produk,harga produk,link gambar,diskon
1232,Nike Vomero Premium Barely Green (Women's),Nike,"IDR 5,900,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1233,Adidas Adizero Evo SL White Black (Women's),Adidas,"IDR 1,680,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 2,500,000"
1234,Nike Moon Shoe SP Jacquemus Fauna Brown (Women's),Nike,"IDR 6,210,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1235,Adidas Samba LT Black White Gum (Women's),Adidas,"IDR 1,330,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1236,Puma Speedcat Ballet Whisp of Pink (Women's),Puma,"IDR 1,210,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,299,000"
1237,Adidas Samba Jane Sandy Pink Cream White Gum (...,Adidas,"IDR 1,600,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1238,Nike Vomero Plus White Dark Hazel Sanddrift Go...,Nike,"IDR 1,300,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 3,135,000"
1239,Adidas Samba Jane Crystal Sky Cream White (Wom...,Adidas,"IDR 1,700,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1240,Air Jordan 1 Low Panda (2023) (Women's),Air Jordan,"IDR 1,320,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1241,Nike Dunk Low Gorge Green Navy (Women's),Nike,"IDR 1,180,000",https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,549,000"

In [16]:
# Menampilkan info data yang berjumlah 1238 range index yang terdiri dari 5 kolom dan hanya 1 data yang berbeda jumlah
# yaitu data diskon dikarenakan tidak setiap produk ada diskonnya.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1242 entries, 0 to 1241
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nama produk   1242 non-null   str
 1   brand produk  1242 non-null   str
 2   harga produk  1242 non-null   str
 3   link gambar   1242 non-null   str
 4   diskon        520 non-null    str
dtypes: str(5)
memory usage: 48.6 KB

In [17]:
# Menampilkan type data masing-masing kolom
df.dtypes

nama produk     str
brand produk    str
harga produk    str
link gambar     str
diskon          str
dtype: object

In [18]:
#Menampilkan jumlah data unique 
df.nunique()

nama produk     1083
brand produk      19
harga produk     278
link gambar     1086
diskon            59
dtype: int64

In [19]:
# menghilangkan IDR dalam Harga produk
df['harga produk'] = df['harga produk'].str.replace('IDR', '', regex=False ) 
# menghilangkan tanda koma (,) pada penulisan harga produk
df['harga produk'] = df['harga produk'].str.replace(',', '', regex=False) 
# mengubah type harga produk yang awalnya str ke float
df['harga produk'] = df['harga produk'].astype(float)

In [20]:
df

,nama produk,brand produk,harga produk,link gambar,diskon
0,Puma Speedcat Ballet Lace Frosted Ivory Ruby S...,Puma,1770000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1,Nike P-6000 White Elemental Pink Metallic Silv...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,729,000"
2,Puma Speedcat Ballet Lace Ruby Shimmer Frosted...,Puma,1800000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
3,Puma Speedcat Ballet Black Mauve Mist (Women's),Puma,1250000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,320,000"
4,Puma Speedcat Ballet Lace Silver (Women's),Puma,1640000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
...,...,...,...,...,...
1237,Adidas Samba Jane Sandy Pink Cream White Gum (...,Adidas,1600000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1238,Nike Vomero Plus White Dark Hazel Sanddrift Go...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 3,135,000"
1239,Adidas Samba Jane Crystal Sky Cream White (Wom...,Adidas,1700000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1240,Air Jordan 1 Low Panda (2023) (Women's),Air Jordan,1320000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,815,000"
1241,Nike Dunk Low Gorge Green Navy (Women's),Nike,1180000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,"IDR 1,549,000"

In [21]:
# menghilangkan IDR dalam diskon
df['diskon'] = df['diskon'].str.replace('IDR', '', regex=False ) 
# menghilangkan tand koma (,) dalam diskon
df['diskon'] = df['diskon'].str.replace(',', '', regex=False) 
# merubah type data yang awalnya str menjadi float/numeric
df['diskon'] = pd.to_numeric(df['diskon'], errors='coerce')

In [22]:
df

,nama produk,brand produk,harga produk,link gambar,diskon
0,Puma Speedcat Ballet Lace Frosted Ivory Ruby S...,Puma,1770000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1,Nike P-6000 White Elemental Pink Metallic Silv...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1729000.0
2,Puma Speedcat Ballet Lace Ruby Shimmer Frosted...,Puma,1800000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
3,Puma Speedcat Ballet Black Mauve Mist (Women's),Puma,1250000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1320000.0
4,Puma Speedcat Ballet Lace Silver (Women's),Puma,1640000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
...,...,...,...,...,...
1237,Adidas Samba Jane Sandy Pink Cream White Gum (...,Adidas,1600000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN
1238,Nike Vomero Plus White Dark Hazel Sanddrift Go...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,3135000.0
1239,Adidas Samba Jane Crystal Sky Cream White (Wom...,Adidas,1700000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1815000.0
1240,Air Jordan 1 Low Panda (2023) (Women's),Air Jordan,1320000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1815000.0
1241,Nike Dunk Low Gorge Green Navy (Women's),Nike,1180000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1549000.0

In [23]:
# menghitung persen diskon dari selisih dari diskon dikurangi harga produk
df['diskon persen'] = ((df['diskon'] - df['harga produk']) / df['diskon'] * 100)
# hasilnya kita pilih batasnya 2 angka di belakang koma dan type nya kita buat menjadi float
df['diskon persen'] = df['diskon persen'].round(2).astype(float)

In [24]:
df

,nama produk,brand produk,harga produk,link gambar,diskon,diskon persen
0,Puma Speedcat Ballet Lace Frosted Ivory Ruby S...,Puma,1770000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
1,Nike P-6000 White Elemental Pink Metallic Silv...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1729000.0,24.81
2,Puma Speedcat Ballet Lace Ruby Shimmer Frosted...,Puma,1800000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
3,Puma Speedcat Ballet Black Mauve Mist (Women's),Puma,1250000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1320000.0,5.30
4,Puma Speedcat Ballet Lace Silver (Women's),Puma,1640000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
...,...,...,...,...,...,...
1237,Adidas Samba Jane Sandy Pink Cream White Gum (...,Adidas,1600000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
1238,Nike Vomero Plus White Dark Hazel Sanddrift Go...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,3135000.0,58.53
1239,Adidas Samba Jane Crystal Sky Cream White (Wom...,Adidas,1700000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1815000.0,6.34
1240,Air Jordan 1 Low Panda (2023) (Women's),Air Jordan,1320000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1815000.0,27.27
1241,Nike Dunk Low Gorge Green Navy (Women's),Nike,1180000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1549000.0,23.82

In [25]:
# Me-rename nama kolom agar lebih mudah di pahami user
df.rename(columns={
    'harga produk': 'harga retail',
    'diskon': 'harga original',
    'diskon persen': 'diskon'
}, inplace = True)

In [26]:
df

,nama produk,brand produk,harga retail,link gambar,harga original,diskon
0,Puma Speedcat Ballet Lace Frosted Ivory Ruby S...,Puma,1770000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
1,Nike P-6000 White Elemental Pink Metallic Silv...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1729000.0,24.81
2,Puma Speedcat Ballet Lace Ruby Shimmer Frosted...,Puma,1800000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
3,Puma Speedcat Ballet Black Mauve Mist (Women's),Puma,1250000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1320000.0,5.30
4,Puma Speedcat Ballet Lace Silver (Women's),Puma,1640000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
...,...,...,...,...,...,...
1237,Adidas Samba Jane Sandy Pink Cream White Gum (...,Adidas,1600000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,NaN,NaN
1238,Nike Vomero Plus White Dark Hazel Sanddrift Go...,Nike,1300000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,3135000.0,58.53
1239,Adidas Samba Jane Crystal Sky Cream White (Wom...,Adidas,1700000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1815000.0,6.34
1240,Air Jordan 1 Low Panda (2023) (Women's),Air Jordan,1320000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1815000.0,27.27
1241,Nike Dunk Low Gorge Green Navy (Women's),Nike,1180000.0,https://cdn-old.kickavenue.com/eyJidWNrZXQiOiJ...,1549000.0,23.82

In [27]:
#cross-check type kolom yang kita ubah
df.dtypes

nama produk           str
brand produk          str
harga retail      float64
link gambar           str
harga original    float64
diskon            float64
dtype: object

In [28]:
df.to_csv('coda_P0M1_Data_Bersih_Herlina.csv',index=False)